### ISSUE TITLE
Support excludes in the plugin.

### ISSUE THREAD

**Issue by orballo** [wp-pwa/wp-pwa-plugin#6] opened 2017-10-23 11:33 UTC
Related issues that should be taken into account:
- Date archive doesn't work correctly (https://github.com/worona/saturn-app-theme-worona/issues/167)

**Comment by luisherranz** [comment] 2018-01-22 09:54
Date archive were excluded by default.

This is a duplicate of #31 so I'm closing it.

**Closed by luisherranz** 2018-01-22 09:54 UTC
